CREATE TABLE tb_starter(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  cpf VARCHAR(255) NOT NULL,
  quatroLetras VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  imagem MEDIUMBLOB
);